### ISSUE TITLE
大兄弟 你咋不搞了

### ISSUE THREAD

**Issue by the6nnoo** [lwlizhe/NovelVideoModuleNovel#1]
大兄弟 你咋不搞了
大兄弟 你咋不搞了
大兄弟 你咋不搞了
大兄弟 你咋不搞了
大兄弟 你咋不搞了

**Comment by lwlizhe** [comment]
额，实现到一半，发现用flutter完全可以实现，基本一个原理，只是实现方式稍微有所差别……所以去做那个flutter_novel项目中了……
